#!/bin/sh /etc/rc.common

START=99
STOP=40
USE_PROCD=1

NAME=openvpn-ubus
PROG="/usr/bin/$NAME"

start_service() {
    procd_open_instance "openvpn-ubus-$1"
    procd_set_param command "$PROG" "--server-name=$1" "--address=$2"
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param pidfile /var/run/openvpn-ubus-"$1".pid
    procd_set_param file /etc/config/openvpn-ubus-"$1"
    procd_close_instance
}

restart() {
    stop
    start
}